site_name: 参与开源
site_url: https://erdengk.github.io/gsoc-analyse/
site_author: erdengk
site_description: >-
  参与开源

repo_name: open-source-analyse
repo_url: https://github.com/erdengk/gsoc-analyse

copyright: Copyright &copy; 2021-present <a href="https://github.com/erdengk" target="_blank" rel="noopener noreferrer">erdengk</a>

theme:
  name: material
  language: zh

  palette:
    primary: blue
    accent: light blue

  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github



  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - search.suggest
    - search.highlight
#    # - navigation.instant
#    # - navigation.expand
#    # - navigation.sections
#    - navigation.tracking
#    # - navigation.tabs
#    # - navigation.tabs.sticky
#    - navigation.top
#    # - navigation.indexes
#    - search.highlight
#    - search.share
#    - search.suggest
#    # - toc.integrate
#    - content.code.annotate
plugins:
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
  - search:
      lang: ja


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/erdengk/gsoc-analyse

nav:
  - 前言: "README.md"
  - GSoC:
    - "GSoC2022": "cn/gsoc/GSoC2022/GSoC2022.md"
    - "GSoC2021": "cn/gsoc/GSoC2021/GSoC2021.md"